services:
  - type: web
    name: yiduluren
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_with_waitress.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: Asia/Shanghai
